# Generated by Django 3.1.13 on 2021-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='آدرس دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها ',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='عنوان کتاب')),
                ('author', models.CharField(max_length=75, verbose_name='نویسنده')),
                ('inventory', models.PositiveIntegerField(verbose_name='تعداد')),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت واحد')),
                ('percent_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف درصدی')),
                ('cash_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف نقدی')),
                ('image', models.ImageField(upload_to='images')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('category', models.ManyToManyField(to='home.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
