# Generated by Django 3.1.13 on 2021-09-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='نام دسته بندی'),
        ),
    ]
